easy_admin:
  entities:
    Commentaire:
        class: App\Entity\Commentaire
        form:
            fields:
            - { property: 'contenu', label: "Contenu"}
        list:
          actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
          fields:
            - { property: 'contenu', label: "Contenu"}